# Generated by Django 4.2.15 on 2024-08-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', '未着手'), ('in_progress', '処理中'), ('processed', '処理済み'), ('completed', '完了'), ('pending', '保留中')], default='not_started', max_length=20),
        ),
    ]
