# Generated by Django 4.2.15 on 2024-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20),
        ),
    ]
